//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 51 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Add Weight
      ///
      /// Key: addWeight
      ///
      /// Locales: en, ru
      var addWeight: RswiftResources.StringResource { .init(key: "addWeight", tableName: "Localizable", source: source, developmentValue: "Add Weight", comment: nil) }

      /// en translation: Beginner
      ///
      /// Key: beginner
      ///
      /// Locales: en, ru
      var beginner: RswiftResources.StringResource { .init(key: "beginner", tableName: "Localizable", source: source, developmentValue: "Beginner", comment: nil) }

      /// en translation: Dips
      ///
      /// Key: dips
      ///
      /// Locales: en, ru
      var dips: RswiftResources.StringResource { .init(key: "dips", tableName: "Localizable", source: source, developmentValue: "Dips", comment: nil) }

      /// en translation: Done
      ///
      /// Key: done
      ///
      /// Locales: en
      var done: RswiftResources.StringResource { .init(key: "done", tableName: "Localizable", source: source, developmentValue: "Done", comment: nil) }

      /// en translation: Exercise
      ///
      /// Key: exercise
      ///
      /// Locales: en
      var exercise: RswiftResources.StringResource { .init(key: "exercise", tableName: "Localizable", source: source, developmentValue: "Exercise", comment: nil) }

      /// en translation: Fri
      ///
      /// Key: fri
      ///
      /// Locales: en, ru
      var fri: RswiftResources.StringResource { .init(key: "fri", tableName: "Localizable", source: source, developmentValue: "Fri", comment: nil) }

      /// en translation: Good job!  You've done %d reps.
      ///
      /// Key: goodJobMessage
      ///
      /// Locales: en, ru
      var goodJobMessage: RswiftResources.StringResource1<Int> { .init(key: "goodJobMessage", tableName: "Localizable", source: source, developmentValue: "Good job!\n You've done %d reps.", comment: nil) }

      /// en translation: Intermediate
      ///
      /// Key: intermediate
      ///
      /// Locales: en, ru
      var intermediate: RswiftResources.StringResource { .init(key: "intermediate", tableName: "Localizable", source: source, developmentValue: "Intermediate", comment: nil) }

      /// en translation: Last session
      ///
      /// Key: lastSession
      ///
      /// Locales: en, ru
      var lastSession: RswiftResources.StringResource { .init(key: "lastSession", tableName: "Localizable", source: source, developmentValue: "Last session", comment: nil) }

      /// en translation: Last 7 sessions
      ///
      /// Key: lastSevenSessions
      ///
      /// Locales: en, ru
      var lastSevenSessions: RswiftResources.StringResource { .init(key: "lastSevenSessions", tableName: "Localizable", source: source, developmentValue: "Last 7 sessions", comment: nil) }

      /// en translation: Level
      ///
      /// Key: level
      ///
      /// Locales: en, ru
      var level: RswiftResources.StringResource { .init(key: "level", tableName: "Localizable", source: source, developmentValue: "Level", comment: nil) }

      /// en translation: Level 1
      ///
      /// Key: level1
      ///
      /// Locales: en, ru
      var level1: RswiftResources.StringResource { .init(key: "level1", tableName: "Localizable", source: source, developmentValue: "Level 1", comment: nil) }

      /// en translation: Level 10
      ///
      /// Key: level10
      ///
      /// Locales: en, ru
      var level10: RswiftResources.StringResource { .init(key: "level10", tableName: "Localizable", source: source, developmentValue: "Level 10", comment: nil) }

      /// en translation: Level 11
      ///
      /// Key: level11
      ///
      /// Locales: en, ru
      var level11: RswiftResources.StringResource { .init(key: "level11", tableName: "Localizable", source: source, developmentValue: "Level 11", comment: nil) }

      /// en translation: Level 12
      ///
      /// Key: level12
      ///
      /// Locales: en, ru
      var level12: RswiftResources.StringResource { .init(key: "level12", tableName: "Localizable", source: source, developmentValue: "Level 12", comment: nil) }

      /// en translation: Level 13
      ///
      /// Key: level13
      ///
      /// Locales: en, ru
      var level13: RswiftResources.StringResource { .init(key: "level13", tableName: "Localizable", source: source, developmentValue: "Level 13", comment: nil) }

      /// en translation: Level 14
      ///
      /// Key: level14
      ///
      /// Locales: en, ru
      var level14: RswiftResources.StringResource { .init(key: "level14", tableName: "Localizable", source: source, developmentValue: "Level 14", comment: nil) }

      /// en translation: Level 15
      ///
      /// Key: level15
      ///
      /// Locales: en, ru
      var level15: RswiftResources.StringResource { .init(key: "level15", tableName: "Localizable", source: source, developmentValue: "Level 15", comment: nil) }

      /// en translation: Level 16
      ///
      /// Key: level16
      ///
      /// Locales: en, ru
      var level16: RswiftResources.StringResource { .init(key: "level16", tableName: "Localizable", source: source, developmentValue: "Level 16", comment: nil) }

      /// en translation: Level 17
      ///
      /// Key: level17
      ///
      /// Locales: en, ru
      var level17: RswiftResources.StringResource { .init(key: "level17", tableName: "Localizable", source: source, developmentValue: "Level 17", comment: nil) }

      /// en translation: Level 18
      ///
      /// Key: level18
      ///
      /// Locales: en, ru
      var level18: RswiftResources.StringResource { .init(key: "level18", tableName: "Localizable", source: source, developmentValue: "Level 18", comment: nil) }

      /// en translation: Level 19
      ///
      /// Key: level19
      ///
      /// Locales: en, ru
      var level19: RswiftResources.StringResource { .init(key: "level19", tableName: "Localizable", source: source, developmentValue: "Level 19", comment: nil) }

      /// en translation: Level 2
      ///
      /// Key: level2
      ///
      /// Locales: en, ru
      var level2: RswiftResources.StringResource { .init(key: "level2", tableName: "Localizable", source: source, developmentValue: "Level 2", comment: nil) }

      /// en translation: Level 20
      ///
      /// Key: level20
      ///
      /// Locales: en, ru
      var level20: RswiftResources.StringResource { .init(key: "level20", tableName: "Localizable", source: source, developmentValue: "Level 20", comment: nil) }

      /// en translation: Level 3
      ///
      /// Key: level3
      ///
      /// Locales: en, ru
      var level3: RswiftResources.StringResource { .init(key: "level3", tableName: "Localizable", source: source, developmentValue: "Level 3", comment: nil) }

      /// en translation: Level 4
      ///
      /// Key: level4
      ///
      /// Locales: en, ru
      var level4: RswiftResources.StringResource { .init(key: "level4", tableName: "Localizable", source: source, developmentValue: "Level 4", comment: nil) }

      /// en translation: Level 5
      ///
      /// Key: level5
      ///
      /// Locales: en, ru
      var level5: RswiftResources.StringResource { .init(key: "level5", tableName: "Localizable", source: source, developmentValue: "Level 5", comment: nil) }

      /// en translation: Level 6
      ///
      /// Key: level6
      ///
      /// Locales: en, ru
      var level6: RswiftResources.StringResource { .init(key: "level6", tableName: "Localizable", source: source, developmentValue: "Level 6", comment: nil) }

      /// en translation: Level 7
      ///
      /// Key: level7
      ///
      /// Locales: en, ru
      var level7: RswiftResources.StringResource { .init(key: "level7", tableName: "Localizable", source: source, developmentValue: "Level 7", comment: nil) }

      /// en translation: Level 8
      ///
      /// Key: level8
      ///
      /// Locales: en, ru
      var level8: RswiftResources.StringResource { .init(key: "level8", tableName: "Localizable", source: source, developmentValue: "Level 8", comment: nil) }

      /// en translation: Level 9
      ///
      /// Key: level9
      ///
      /// Locales: en, ru
      var level9: RswiftResources.StringResource { .init(key: "level9", tableName: "Localizable", source: source, developmentValue: "Level 9", comment: nil) }

      /// en translation: Main
      ///
      /// Key: main
      ///
      /// Locales: en, ru
      var main: RswiftResources.StringResource { .init(key: "main", tableName: "Localizable", source: source, developmentValue: "Main", comment: nil) }

      /// en translation: Mon
      ///
      /// Key: mon
      ///
      /// Locales: en, ru
      var mon: RswiftResources.StringResource { .init(key: "mon", tableName: "Localizable", source: source, developmentValue: "Mon", comment: nil) }

      /// en translation: No data available
      ///
      /// Key: noData
      ///
      /// Locales: en, ru
      var noData: RswiftResources.StringResource { .init(key: "noData", tableName: "Localizable", source: source, developmentValue: "No data available", comment: nil) }

      /// en translation: Pro
      ///
      /// Key: pro
      ///
      /// Locales: en, ru
      var pro: RswiftResources.StringResource { .init(key: "pro", tableName: "Localizable", source: source, developmentValue: "Pro", comment: nil) }

      /// en translation: Progress
      ///
      /// Key: progress
      ///
      /// Locales: en, ru
      var progress: RswiftResources.StringResource { .init(key: "progress", tableName: "Localizable", source: source, developmentValue: "Progress", comment: nil) }

      /// en translation: Pull-ups
      ///
      /// Key: pullups
      ///
      /// Locales: en, ru
      var pullups: RswiftResources.StringResource { .init(key: "pullups", tableName: "Localizable", source: source, developmentValue: "Pull-ups", comment: nil) }

      /// en translation: reps
      ///
      /// Key: reps
      ///
      /// Locales: en, ru
      var reps: RswiftResources.StringResource { .init(key: "reps", tableName: "Localizable", source: source, developmentValue: "reps", comment: nil) }

      /// en translation: Reps
      ///
      /// Key: repsCaps
      ///
      /// Locales: en, ru
      var repsCaps: RswiftResources.StringResource { .init(key: "repsCaps", tableName: "Localizable", source: source, developmentValue: "Reps", comment: nil) }

      /// en translation: Sat
      ///
      /// Key: sat
      ///
      /// Locales: en, ru
      var sat: RswiftResources.StringResource { .init(key: "sat", tableName: "Localizable", source: source, developmentValue: "Sat", comment: nil) }

      /// en translation: Set
      ///
      /// Key: set
      ///
      /// Locales: en, ru
      var set: RswiftResources.StringResource { .init(key: "set", tableName: "Localizable", source: source, developmentValue: "Set", comment: nil) }

      /// en translation: Sets
      ///
      /// Key: sets
      ///
      /// Locales: en, ru
      var sets: RswiftResources.StringResource { .init(key: "sets", tableName: "Localizable", source: source, developmentValue: "Sets", comment: nil) }

      /// en translation: Start
      ///
      /// Key: start
      ///
      /// Locales: en, ru
      var start: RswiftResources.StringResource { .init(key: "start", tableName: "Localizable", source: source, developmentValue: "Start", comment: nil) }

      /// en translation: Start Exercise
      ///
      /// Key: startExercise
      ///
      /// Locales: en, ru
      var startExercise: RswiftResources.StringResource { .init(key: "startExercise", tableName: "Localizable", source: source, developmentValue: "Start Exercise", comment: nil) }

      /// en translation: Stats
      ///
      /// Key: stats
      ///
      /// Locales: en, ru
      var stats: RswiftResources.StringResource { .init(key: "stats", tableName: "Localizable", source: source, developmentValue: "Stats", comment: nil) }

      /// en translation: Sun
      ///
      /// Key: sun
      ///
      /// Locales: en, ru
      var sun: RswiftResources.StringResource { .init(key: "sun", tableName: "Localizable", source: source, developmentValue: "Sun", comment: nil) }

      /// en translation: Thu
      ///
      /// Key: thu
      ///
      /// Locales: en, ru
      var thu: RswiftResources.StringResource { .init(key: "thu", tableName: "Localizable", source: source, developmentValue: "Thu", comment: nil) }

      /// en translation: Training
      ///
      /// Key: training
      ///
      /// Locales: en, ru
      var training: RswiftResources.StringResource { .init(key: "training", tableName: "Localizable", source: source, developmentValue: "Training", comment: nil) }

      /// en translation: Training history
      ///
      /// Key: trainingHistory
      ///
      /// Locales: en, ru
      var trainingHistory: RswiftResources.StringResource { .init(key: "trainingHistory", tableName: "Localizable", source: source, developmentValue: "Training history", comment: nil) }

      /// en translation: Tue
      ///
      /// Key: tue
      ///
      /// Locales: en, ru
      var tue: RswiftResources.StringResource { .init(key: "tue", tableName: "Localizable", source: source, developmentValue: "Tue", comment: nil) }

      /// en translation: Wed
      ///
      /// Key: wed
      ///
      /// Locales: en, ru
      var wed: RswiftResources.StringResource { .init(key: "wed", tableName: "Localizable", source: source, developmentValue: "Wed", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 6 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Image`.
    var image: RswiftResources.ImageResource { .init(name: "Image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dips`.
    var dips: RswiftResources.ImageResource { .init(name: "dips", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dips2`.
    var dips2: RswiftResources.ImageResource { .init(name: "dips2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `metalTexture`.
    var metalTexture: RswiftResources.ImageResource { .init(name: "metalTexture", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pull-ups`.
    var pullUps: RswiftResources.ImageResource { .init(name: "pull-ups", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pullup`.
    var pullup: RswiftResources.ImageResource { .init(name: "pullup", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }
}